---
- name: Restart primary MySQL
  ansible.builtin.systemd:
    name: mysql
    state: restarted

- name: Restart rsyslog for primary MySQL
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Run initial database backup
  ansible.builtin.systemd:
    name: borg-mysql-backup.service
    state: started
