Vagrant.configure("2") do |config|
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "almalinux/9"
    nginx.vm.hostname = "nginx"

    nginx.vm.network "private_network", ip: "192.168.56.10"

    nginx.vm.provider "virtualbox" do |vb|
      vb.name = "nginx"
      vb.memory = 1024
      vb.cpus = 1
    end

    nginx.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/start.yml"
    end
  end
end
