machines = [
  { name: "backup", ip: "192.168.56.10" },
  { name: "client", ip: "192.168.56.15" }
]

Vagrant.configure("2") do |config|
  machines.each do |m|
    config.vm.define m[:name] do |vr|
      vr.vm.box = "debian/bookworm64"

      vr.vm.network "private_network", ip: m[:ip]

      if m[:name] == "backup"
        vr.vm.disk :disk, size: "2GB", name: "backup_disk"
      end

      vr.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
        vb.name = m[:name]
      end

      if m[:name] == "client"
        vr.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible/provision.yml"
          ansible.limit = "all"
        end
      end
    end
  end
end
