Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provider "vmware_desktop" do |v|
    v.memory = 2048
    v.cpus = 2
    v.gui = false
  end

  config.vm.provision "shell", path: "provision-watchlog.sh"
end
