Vagrant.configure("2") do |config|
  config.vm.define "authentication-test" do |vr|
    vr.vm.box = "almalinux/9"

    vr.vm.network "private_network", ip: "192.168.56.10"

    vr.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "authentication-test"
      vb.customize ['modifyvm', :id, '--audio', 'none']
    end

    vr.vm.provision "shell", path: "provision.sh"
  end
end
