Vagrant.configure(2) do |config|
  config.vm.box_check_update = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/provision.yml"
    ansible.verbose = "v"
    ansible.inventory_path = "ansible/hosts"
    ansible.host_key_checking = "false"
    ansible.become = "true"
  end
  
  config.vm.define "AppServer" do |vmconfig| 
    vmconfig.vm.box = "generic/debian12"
    vmconfig.vm.hostname = "AppServer"
    
    config.vm.network "private_network", ip: "192.168.56.10"

    vmconfig.vm.network "forwarded_port", guest: 8081, host: 8081
    vmconfig.vm.network "forwarded_port", guest: 8082, host: 8082
    vmconfig.vm.network "forwarded_port", guest: 8083, host: 8083
    
    vmconfig.vm.provider "virtualbox" do |vbx|
      vbx.memory = "8192"
      vbx.cpus = "4"
    end
  end
end
